//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueStatu
    {
        public int QueueId { get; set; }
        public string TaskName { get; set; }
        public string TaskStatus { get; set; }
        public string QueueStatus { get; set; }
        public string Priority { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public int UserId { get; set; }
    }
}
