//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskQueue
    {
        public int QueueId { get; set; }
        public int TaskId { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExecutionDate { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
