//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLog
    {
        public int LogId { get; set; }
        public int TaskId { get; set; }
        public string LogMessage { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
